### PR TITLE
Accept float values in financial summary

### PR DESCRIPTION
**Pull request by noelzubin**

### CODE REVIEW

**Review by alvarobartt — APPROVED** [review]

**Comment by alvarobartt** [comment]
Thank you so much @noelzubin! I will get back to investpy in 1 week or so, as I have been pretty busy, thank you for contributing.

In order to get the latest updates you can follow me on Twitter at https://twitter.com/alvarobartt

**Comment by anhanh11001** [comment]
@alvarobartt Hey, any chances we can get this small patch released? Maybe something like v1.0.1

Btw, great package. Thanks a lot for making this open-source

**Comment by alvarobartt** [comment]
Hi @anhanh11001! Thanks for your kind words towards my work with `investpy`, much appreciated! 🤗 Then regarding this PR, it's already merged on the master branch, later this night I'll create the 1.0.1 as you suggest. But in the meantime you can install the source version with the fix so that you don't run onto this problem again, to do so, please use the following command:

``pip install git+https://github.com/alvarobartt/investpy.git@master``

Remember to star the repo, follow me here and on Twitter at https://twitter.com/alvarobartt so as to get notified of all the updates and projects I'm working on! ⭐

**Comment by anhanh11001** [comment]
It works like a charm 🚀 

Thanks for the fast response. In case you need help on improving this lib, I'd like to help with contributing.

**Pull request merged**
