### PR TITLE
Remove debug print statement

### PR DESCRIPTION
**Pull request by DouweM**

### CODE REVIEW

**Comment by alvarobartt** [comment]
Hi @DouweM, thank you for spotting this! Anyway, this is solved in the `dev` branch that will be merged later this week... Sorry for the inconvenience, hope I can merge it ASAP. But thanks anyway for contributing 🧙🏻 

P.S.: here you have the code in the `dev` branch

https://github.com/alvarobartt/investpy/blob/298ee0a2df9e721c290ca08e724846bce173a2a0/investpy/search.py#L150-L156

**Comment by alvarobartt** [comment]
To give you more insight I'm currently working on the development of a function to search not just quotes but also economic events as some users requested it, so hopefully later this week I'll release the `v1.0.4` 👍🏻

**Comment by DouweM** [comment]
@alvarobartt Ah, cool, looking forward to v1.0.4 then! I needs this fix quick to be able to use investpy in https://gitlab.com/DouweM/tap-investing :)

**Comment by alvarobartt** [comment]
Sure! Consider it done before this weekend 👍🏻

**Pull request closed without merging**
